Cleanup & Bugfixes on Ubuntu 16.04

diff --git a/available.d/fail2ban b/available.d/fail2ban
--- a/available.d/fail2ban
+++ b/available.d/fail2ban
@@ -1,4 +1,8 @@
 #!/bin/bash
-last_f2b=$(if [[ -e /var/log/fail2ban.log ]]; then tail -n1 /var/log/fail2ban.log || echo "Permission denied"; else echo "No Fail2ban"; fi)
+# last_f2b=$(if [[ -e /var/log/fail2ban.log ]]; then tail -n1 /var/log/fail2ban.log || echo "Permission denied"; else echo "No Fail2ban"; fi)
 
-echo -e "\033[0;35m+     \033[0;37mFail2ban \033[0;35m= \033[1;32m$last_f2b"
+if [[ -e /var/log/fail3ban.log ]]; then
+  last_f2b=$(tail -n1 /var/log/fail2ban.log || echo "Permission denied")
+  echo -e "\033[0;35m+     \033[0;37mFail2ban \033[0;35m= \033[1;32m$last_f2b"
+fi
+
